server:
  port: 8081

app:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_please_32+_chars_1234567890"
    issuer: "account-service"
    expire-minutes: 60

spring:
  application:
    name: account-service


  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/accountdb}
    username: ${SPRING_DATASOURCE_USERNAME:account}
    password: ${SPRING_DATASOURCE_PASSWORD:accountpwd}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      open-in-view: false


management:
  endpoints:
    web:
      exposure:
        include: health,info