server:
  port: 8082

spring:
  application:
    name: item-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/itemdb}

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_please_32+_chars_1234567890"