services:
  postgres:
    image: postgres:16
    container_name: shopping-postgres
    environment:
      POSTGRES_DB: accountdb
      POSTGRES_USER: account
      POSTGRES_PASSWORD: accountpwd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: shopping-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata: